sudo: false
language: python
python: 
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox-travis
  - pip install coveralls

script:
  - tox

after_success: coveralls
